project_id = "tffxaagmecmsgiltdjzv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
enable_signup = true
email_confirm = false
email_double_confirm_changes = false
enable_manual_linking = false

[functions.check-promo-usage]
verify_jwt = false

[functions.use-promo-code]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.send-application]
verify_jwt = false

[functions.send-application-response]
verify_jwt = false